config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'static_pages/hotel'
  get 'static_pages/menu'

  root 'static_pages#home'
  get '/photos', to: 'static_pages#photos'
  get '/registries', to: 'static_pages#registries'
  get '/info', to: 'static_pages#hotel'
  get '/menu', to: 'static_pages#menu'
  get '/register', to: 'static_pages#register'
  post '/register', to: 'users#create'
  post 'guests/:id/rsvp', to: 'users#edit'
  get '/guestlist', to: 'users#guestlist'
  get '/schedule', to: 'static_pages#schedule'
  get '/confirmrsvp', to: 'static_pages#rsvp'
  get '/decline', to: 'static_pages#decline'
  post '/decline', to: 'static_pages#decline'
  get '/inviteall', to: 'users#invite_all_guests'
  
  resources :users, :path => "guests", path_names: { edit: 'rsvp', edit_registerform: 'register' } do
    member do
      get :edit_registerform
      put :update_registerform
      get :invitation
      get :decline
      get :accept
      get :send_invitation_email
    end
  end
  
  # resources :users, :path => "guests", path_names: { edit: 'update' }
  
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email = email.downcase }
  before_save {self.name = name.titleize}
  validates :name, presence: true, length: {maximum: 50 }, uniqueness: {case_sensitive: false }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: {case_sensitive: false }
  # validates :registernote, presence: true, length: { maximum: 500 }
  # validates :guestone, uniqueness: {case_sensitive: false }
  # validates :guesttwo, uniqueness: {case_sensitive: false }
  # validates :guestthree, uniqueness: {case_sensitive: false }
  # validates :guestfour, uniqueness: {case_sensitive: false }
  # validates :guestfive, uniqueness: {case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  skip_before_filter :verify_authenticity_token
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  
  def contact
  end
  
  def registries
  end
  
  def register
  end
  
  def photos
  end

  
  def hotel
  end

  def menu
  end
  
  def schedule
  end
  
  def rsvp
  end
  
  def decline
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :invitation]
  # before_action :logged_in_user, only: [:index]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end
  
  def guestlist
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end
  
  def edit_registerform
    @user = User.find(params[:id])
  end
  
  def update_registerform
    @user = User.find(params[:id])
  end
  
  def invitation
    @user = User.find(params[:id])
  end
  
  def send_invitation_email
    @user = User.find(params[:id])
    UserMailer.invitation(@user).deliver_later
    
    redirect_to guestlist_path
  end
  
  def invite_all_guests
    @users = User.all
    @users.each do |user|
      UserMailer.invitation(user).deliver_later
    end
    redirect_to guestlist_path
  end
  
  
  def accept
    @user = User.find(params[:id])
    @user.rsvp = true
    @user.save
    redirect_to edit_user_path(@user)
  end
  
  def decline
    @user = User.find(params[:id])
    @user.rsvp = false
    @user.save
    UserMailer.rsvp_user(@user).deliver_later
    UserMailer.rsvp_self(@user).deliver_later
    redirect_to decline_path
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        UserMailer.invitation(@user).deliver_later
        UserMailer.new_self(@user).deliver_later
        flash[:success] = "You are now registered! Check your email for confirmation!"
        format.html { redirect_to guestlist_path }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      # puts '---------------------------------------------------------'
      # puts @user
      # puts user_params
      # puts format
      # puts '---------------------------------------------------------'
      # puts @user.test
      if @user.update(user_params)
          if @user.rsvp?
            UserMailer.rsvp_user(@user).deliver_later
            UserMailer.rsvp_self(@user).deliver_later
          else
          end
          flash[:success] = "Your RSVP has been submitted, check your email for confirmation!"
          format.html { redirect_to @user }
          format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      # params.require(:user).permit(:name, :email, :registernote, :invitationoptout, :rsvp, :plus_one, :veg, :plus_one_veg)
      params.require(:user).permit(:name, :email, :registernote, :invitationoptout, :numguests, :invitationid, :allergies, :suggestedsong, :veg, :guestone, :guesttwo, :guestthree, :guestfour, :guestfive)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.       # Documentation comment
  def full_title(page_title = '')                     # Method def, optional arg
    base_title = "Ruby on Rails Tutorial Sample App"  # Variable assignment
    if page_title.empty?                              # Boolean test
      base_title                                      # Implicit return
    else
      page_title + " | " + base_title                 # String concatenation
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<!--<footer class="footer">-->
<!--  <small>-->
<!--    <%#= link_to "Contact Us", contact_path %>-->
<!--  </small>-->
<!--</footer>-->

app/views/layouts/_header.html.erb
  <header>
      <!--<nav class = "navbar navbar-default navbar-fixed-top">-->
      <!--  <div class = "container-fluid">-->
      <!--    <div class = "navbar-header">-->
      <!--      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar" aria-expanded="false">-->
      <!--        <span class="icon-bar"></span>-->
      <!--        <span class="icon-bar"></span>-->
      <!--        <span class="icon-bar"></span>-->
      <!--      </button>-->
      <!--      <%#= link_to image_tag("shapirowedding.PNG", alt: "Shapiro Wedding"), root_path, id: "homelogo" %>-->
      <!--    </div>-->
      <!--    <div class="collapse navbar-collapse" id="myNavbar">-->
      <!--      <ul class = "nav navbar-nav navbar-right">-->
      <!--        <li> <#%= link_to "Home", root_path %></li>-->
      <!--        <li> <#%= link_to "Register", register_path %></li>-->
      <!--        <li> <#%= link_to "Photos", photos_path %></li>-->
      <!--        <li> <#%= link_to "Registries", registries_path %></li>-->
      <!--        <li> <#%= link_to "Information", info_path %></li>-->
      <!--      </ul>-->
      <!--    </div>-->
      <!--  </div>-->
      <!--</nav>-->
      <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
          <div class="navbar-header">
            <%= link_to image_tag("shapirowedding.PNG", alt: "Shapiro Wedding"), root_path, id: "homelogo" %>
          </div>
          <ul class="nav navbar-nav navbar-right">
            <li> <%= link_to "Home", root_path %></li>
            <!--<li> <#%= link_to "Register", register_path %></li>-->
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">Info
              <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li> <%= link_to "Photos", photos_path %></li>
                <li> <%= link_to "Registries", registries_path %></li>
                <li> <%= link_to "Hotel", info_path %></li>
                <li> <%= link_to "Schedule", schedule_path %></li>
              </ul>
            </li>
          </ul>
        </div>
      </nav>
  </header>
  
  

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Shapiro Wedding</title>
    
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%#= javascript_include_tag "/javascripts/jquery-3.1.0.min.js", "/javascripts/app.js", "application", 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "/javascripts/jquery-3.1.0.min.js", "/javascripts/bootstrap.min.js", "/javascripts/app.js", 'data-turbolinks-track': 'reload' %>
    
    <%= render 'layouts/shim' %>
    
  </head>

  <body>
    <%= render 'layouts/header' %>
    
    
    <div class = "container-fluid">
      <div class = "flashmsg center">
        <% flash.each do |message_type, message| %>
          <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
        <% end %>
      </div>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation center">
    <div class="alert alert-danger center">
      Your RSVP contains <%= pluralize(@user.errors.count, "error") %>.
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    
  </div>
<% end %>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact Information</h1>
<p>
  If you have any questions, or need to make any changes to your RSVP, feel free to contact us!
</p>
<ul class = "contactlist">
  <li>69 Greenfield, Irvine, CA, 92614</li>
  <li>Neil's Phone Number: (949)344-1955</li>
  <li>Terra's Phone Number: (949)344-1970</li>
  <li>Email us!</li>
</ul>

app/views/static_pages/decline.html.erb
<% provide(:title, "Declined") %>
<!doctype html>
<body>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 col-xs-6 col-xs-offset-3 col-sm-6 col-sm-offset-3 center">
        <h1>Thank you for your response.</h1>
        <p>We're so sorry to hear you can't make it, you will be greatly missed!<br></p>
        <p>Sending all our love,<br>
        Terra and Neil</p>
    </div>
  </div>
</div>

</body>
</html>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<!doctype html>
<body>
<div class="homepage">
    <div class="row">
        <div class="col-lg-3 col-lg-offset-3 col-md-4 col-md-offset-2 col-sm-4 col-sm-offset-1 col-xs-6 center" >
            <div class="prepare">
                <br><br><br><br><br><br><br><br><br><br>
                <h1>Prepare for joy,<br>prepare for life.</h1>
                <p>Nothing sounds better than celebrating<br>our marriage with the people closest to us.</p>
                <p><strong>We hope to see you there!</strong></p>
            </div>
        </div>
        <div class="col-lg-4 col-lg-offset-0 col-md-5 col-md-offset-0 col-sm-6 col-sm-offset-1 col-xs-6 center">
            <br><br><h1>WeddingSchedule</h1>
            <h3><br>Thursday</h3>
            <p></p>
            <p>3:00PM -- Terra & Neil check in at the Hotel<br>
            6:30PM -- Ceremony Rehearsal Begins<br>
            7:30PM -- Reheasal Dinner @ Brendan's Irish Pub</p>
            <h3>Friday</h3>
            <p>6:30AM - 9:30AM -- Hotel Breakfast<br>
            10:00AM -- Preparations begin<br>
            11:00AM -- Terra goes to Nail Salon<br>
            2:00PM -- Reception Space opens for decoration<br>
            9:00PM -- Drinks @ Brendan's Irish Pub<br>
            </p>
            <h3>Saturday</h3>
            <p>6:30AM - 9:30AM -- Hotel Breakfast<br>
            4:30PM -- Ceremony begins<br>
            5:00PM -- Cocktail Hour & Pictures<br>
            7:00PM -- Dinner is served<br>
            8:30PM -- Let there be cake!<br>
            11:00PM -- Closing time<br>
            </p>
            <h3>Sunday</h3>
            <p>6:30AM - 9:30AM -- Hotel Breakfast<br>
            8:00AM -- Neil & Terra leave for LAX</p>
        </div>
    </div>
    <!--<div class="row">-->
    <!--    <div class="col-lg-3 col-lg-offset-3 col-md-4 col-md-offset-2 col-sm-4 col-sm-offset-0 col-xs-6 center" >-->
    <!--        <br><br><h1>WeddingSchedule</h1>-->
    <!--        <h3><br>Thursday</h3>-->
    <!--        <p></p>-->
    <!--        <p>3:00PM -- Terra & Neil check in at the Hotel<br>-->
    <!--        6:30PM -- Ceremony Rehearsal Begins<br>-->
    <!--        7:30PM -- Reheasal Dinner @ Brendan's Irish Pub</p>-->
    <!--        <h3>Friday</h3>-->
    <!--        <p>6:30AM - 9:30AM -- Hotel Breakfast<br>-->
    <!--        10:00AM -- Preparations begin<br>-->
    <!--        11:00AM -- Terra goes to Nail Salon<br>-->
    <!--        2:00PM -- Reception Space opens for decoration<br>-->
    <!--        9:00PM -- Drinks @ Brendan's Irish Pub<br>-->
    <!--        </p>-->
    <!--        <h3>Saturday</h3>-->
    <!--        <p>6:30AM - 9:30AM -- Hotel Breakfast<br>-->
    <!--        4:30PM -- Ceremony begins<br>-->
    <!--        5:00PM -- Cocktail Hour & Pictures<br>-->
    <!--        7:00PM -- Dinner is served<br>-->
    <!--        8:30PM -- Let there be cake!<br>-->
    <!--        11:00PM -- Closing time<br>-->
    <!--        </p>-->
    <!--        <h3>Sunday</h3>-->
    <!--        <p>6:30AM - 9:30AM -- Hotel Breakfast<br>-->
    <!--        8:00AM -- Neil & Terra leave for LAX</p>-->
    <!--    </div>-->
    <!--    <div class="col-lg-4 col-lg-offset-0 col-md-offset-0 col-sm-4 col-sm-offset-1 col-xs-6 center">-->
    <!--        <div id="wrapper">-->
    <!--            <#%= image_tag("wedding_invitation_opt2.png", alt: "Wedding Invitation", id: "savethedate") %>-->
    <!--        </div>-->
    <!--    </div>-->
    <!--</div>-->
</div>

<div class="contactinfo">
    <br><br><h4>
      If you have any questions, or need to make any changes to your information, feel free to contact us!
    </h4>
    <div class="row">
        <div class="col-md-3 col-md-offset-3 col-sm-3 col-sm-offset-3 center">
            <ul>
                <strong>Contact Neil</strong>
                <li>(949)344-1955</li>
                <li>nshapiro91@gmail.com</li>
            </ul>
        </div>
        <div class="visible-xs"><br></div>
        <div class="col-lg-3 col-lg-offset-0 col-md-3 col-sm-3 col-sm-offset-1 center">
            <ul>
                <strong>Contact Terra</strong>
                <li>(949)344-1970</li>
                <li>terrasmiddy@cox.net</li>
            </ul>
        </div>
    </div>
</div>

</body>
</html>

app/views/static_pages/menu.html.erb
<% provide(:title, "Menu") %>
<!doctype html>
<body>
<div class="container-fluid">
    <div class="receptionmenu">
            <h1>Reception Menu</h1>
            <h2>Appetizers</h2>
            <p>Sausage Stuffed Mushrooms<br>
            Bruschetta</p>
            <h2>Salad</h2>
            <p>Mixed Berry Salad</p>
            <h2>Entrees</h2>
            <p>Chicken Marsala<br>
            Braised Short Rib</p>
            <h2>Sides</h2>
            <p>Garlic Mashed Potatoes and Gravy<br>
            Almond Butter Green Beans</p>
            <h2>Beer & Wine</h2>
            <p>Guiness Harp<br>
            Firestone 805<br>
            Firestone DBA<br>
            Ballast Point Sculpin IPA
            <br><br>Liquor also available at the bar</p>
        </div>
    </div>
</div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

</body>
</html>

app/views/static_pages/register.html.erb
<% provide(:title, 'Register') %>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 col-xs-12">
            <h1>Sorry!</h1>
            <p>The registration period has closed. 
            <br>If you were not able to register in time, please contact us.</p>
        </div>
    </div>
</div>    
<br>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2">
        <%= form_for(@user, url: register_path) do |f| %>
          <%= render 'shared/error_messages' %>
          <h1><%= f.object.name %>,</h1>
          <p><strong>please fill out the name of each guest who will be attending.<br>Names will be printed exactly as written.</strong></p>

          <%= f.label "Guests" %>
          <% if @user.guestone? %>
            <%= f.text_field :guestone, class: 'form-control' %>
          <% elsif %>
            <%= f.text_field :guestone, class: 'form-control', value: f.object.name %>
          <% end %>
          <% if f.object.numguests == 2 %>
            <%= f.text_field :guesttwo, class: 'form-control' %>
          <% elsif f.object.numguests == 3 %>
            <%= f.text_field :guesttwo, class: 'form-control' %>
            <%= f.text_field :guestthree, class: 'form-control' %>
          <% elsif f.object.numguests == 4 %>
            <%= f.text_field :guesttwo, class: 'form-control' %>
            <%= f.text_field :guestthree, class: 'form-control' %>
            <%= f.text_field :guestfour, class: 'form-control' %>
          <% elsif f.object.numguests == 5 %>
            <%= f.text_field :guesttwo, class: 'form-control' %>
            <%= f.text_field :guestthree, class: 'form-control' %>
            <%= f.text_field :guestfour, class: 'form-control' %>
            <%= f.text_field :guestfive, class: 'form-control' %>
          <% else %>
          <% end %>
  
          <%= f.label "How many members of your party will need a vegetarian option?" %>
          <% if @user.veg? %>
            <%= f.number_field :veg, class: 'form-control', in: 0...6 %>
          <% else %>
            <%= f.number_field :veg, class: 'form-control', value: 0, in: 0...6 %>
          <% end %>
          
          <%= f.label "Please list any food allergies for your party" %>
          <%= f.text_field :allergies, class: 'form-control' %>          
          
          <%= f.label "Please list any songs you would like to hear at our wedding:" %>
          <%= f.text_area :suggestedsong, class: 'form-control' %>        
          
          <%= f.hidden_field :test, class: 'form-control', value: true %>
          <!--<input type="hidden" name="test" value="true"/>-->
          
          <br>
          <br>
          <%= f.submit "Submit my RSVP!", class: "btn btn-primary btn-sm" %>
        <% end %>
      </div>
    </div>
  </div>

<% end %>

app/views/users/_registerform.html.erb
<%= form_for(user) do |f| %>
<!--, url: update_registerform_user_path(@user)-->
  
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2">
          <%= form_for(@user, url: register_path) do |f| %>
            <%= render 'shared/error_messages' %>
            <h3>Registration for </h3>
            <h1><%= f.object.name %></h1>

            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
      
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>
            
            <%= f.label "Number of guests" %>
            <% if @user.numguests? %>
              <%= f.number_field :numguests, class: 'form-control', in: 0...6 %>
            <% else %>
              <%= f.number_field :numguests, class: 'form-control', value: 1, in: 0...6 %>
            <% end %>
            
            <br>
            <br>
            
            <%= f.submit "Register for my invitation!", class: "btn btn-primary btn-sm" %>
          <% end %>
        </div>
      </div>
    </div>
  

<% end %>

app/views/users/edit.html.erb
<% provide(:title, "RSVP") %>
<%= render 'form', user: @user %>

app/views/users/edit_registerform.html.erb
<% provide(:title, "Registration Update") %>

<!--<#%= render 'form', user: @user %>-->
<%= render 'registerform', user: @user %>

app/views/users/guestlist.html.erb
<p id="notice"><%= notice %></p>
<% provide(:title, "Guest List") %>
<h1>Wedding Guests</h1>

<table class="table-striped" width="1600px">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>RSVP</th>
      <th>Guest Count</th>
      <th>Guest One</th>
      <th>Guest Two</th>
      <th>Guest Three</th>
      <th>Guest Four</th>
      <th>Guest Five</th>
      <th>Vegetarians</th>
      <th>Allergies</th>
      <th>Songs</th>
      <!--<th colspan="3"></th>-->
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td width="150px"><%= user.name %></td>
        <td><%= user.email %></td>
        <td width="110px">
          <% if user.rsvp.nil? %>
            No Response
          <% else %>
            <% if user.rsvp == true %>
              Attending
            <% else %>
              Not Attending
            <% end %>
          <% end %>
        </td>
        <td><%= user.numguests %></td>
        <td><%= user.guestone %></td>
        <td><%= user.guesttwo %></td>
        <td><%= user.guestthree %></td>
        <td><%= user.guestfour %></td>
        <td><%= user.guestfive %></td>
        <td><%= user.veg %></td>
        <td><%= user.allergies %></td>
        <td><%= user.suggestedsong %></td>
        <!--<td>#%= link_to 'Invitation', invitation_user_path(user), class: "btn btn-default btn-xs" %></td>-->
        <td><%= link_to 'Register', edit_registerform_user_path(user), class: "btn btn-default btn-xs" %></td>
        <td><%= link_to 'RSVP', edit_user_path(user), class: "btn btn-default btn-xs" %></td>
        <td><%= link_to 'Invite Guest', send_invitation_email_user_path(user), class: "btn btn-default btn-xs" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br><br>
<%= link_to 'Add Guest', new_user_path, class: "btn btn-default btn-sm" %>
<%= link_to 'Invite Guests', inviteall_path, class: "btn btn-default btn-sm" %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<% provide(:title, "Registered Guests") %>
<h1>Registered Guests</h1>


  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Requested Invitation</th>
      </tr>
    </thead>
    
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td>
            <% if user.invitationoptout? %>
              No
            <% else %>
              Yes
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

<br>

<!--<%#= link_to 'New User', new_user_path %>-->

app/views/users/new.html.erb
<% provide(:title, 'New Guest') %>
<%= render 'registerform', user: @user %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<!doctype html>

<!--#<p id="notice"><%#= notice %></p>-->

<div class="container-fluid">
  <div class="row">
    <div class="center col-sm-8 col-sm-offset-2">
      <h1><%= @user.name %>,</h1>
      <p><strong>thank you for submitting your RSVP.<br>
      
      <br>We are so glad to hear you will be joining us on March 25th!</strong><br>
      <% if @user.guestfive?%>
        You have submitted a RSVP for 5 guests<br>
      <% elsif @user.guestfour? %>
        You have submitted a RSVP for 4 guests<br>
      <% elsif @user.guestthree? %>
        You have submitted a RSVP for 3 guests<br>
      <% elsif @user.guesttwo? %>
        You have submitted a RSVP for 2 guests<br>
      <% elsif @user.guestone? %>
        You have submitted a RSVP for 1 guest<br>
      <% end %>

      
      1: <%= @user.guestone %><br>
      <% if @user.guestfive? %>
        2: <%= @user.guesttwo %><br>
        3: <%= @user.guestthree %><br>
        4: <%= @user.guestfour %><br>
        5: <%= @user.guestfive %><br>
      <% elsif @user.guestfour? %>
        2: <%= @user.guesttwo %><br>
        3: <%= @user.guestthree %><br>
        4: <%= @user.guestfour %><br>
      <% elsif @user.guestthree? %>
        2: <%= @user.guesttwo %><br>
        3: <%= @user.guestthree %><br>
      <% elsif @user.guesttwo? %>
        2: <%= @user.guesttwo %><br>
      <% end %>
      </p>
      
      <p>
        <% if @user.veg == 1 && @user.allergies?%>
          You will receive <%= @user.veg %> vegetarian plate
        <% elsif @user.veg == 0 %>
          You will not require any vegetarian plates
        <% else %>
          You will receive <%= @user.veg %> vegetarian plates
        <% end %>
      
        <% if @user.allergies? %>
          and have indicated someone in your party has an allergy. Thank you for letting us know!<br>
          Please ensure that the allergy information below is correct:<br><br>
          <%= @user.allergies %><br>
        <% else %>
            .<br>
        <% end %>
      
      <!--<%# if @user.suggestedsong? %>-->
      <!--  <p>-->
      <!--    <strong>Thank you so much for suggesting a song.</strong><br>-->
      <!--    Please review your suggestion below to ensure it is correct:<br><br>-->
      <!--    <%#= @user.suggestedsong %>-->
      <!--  </p><br>-->
      <!--<%# end %>-->
      
      <p>This is an adult only event, so please leave all small children at home.<br>
      There will be a partially hosted bar, which will serve free drinks to start the night.<br><br>
      <strong>Make sure to book your rooms by March 1st in order to receive the wedding block discount.</strong><br>
      Please browse our website for more information, and periodically check the <%= link_to "Schedule", schedule_path %> page as further updates are posted.</p>
      <h3>We can't wait to see you there!</h3>
      
      


    </div>
  </div>
  <div class="center">
    <br>
    <%= link_to 'Wait, I need to edit my RSVP!', edit_user_path(@user), class:"btn btn-primary col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-12", style: "color:white" %>
  </div>
</div>